server:
  address: 127.0.0.1
  port: 80
  servlet:
    session:
      timeout: 15m

spring:
  application:
    name: pickup-web
  output:
    ansi:
      enabled: detect

logging:
  register-shutdown-hook: true