server:
  address: 127.0.0.1
  port: 80
  servlet:
    session:
      timeout: 15m
  ssl:
    enabled: true
    key-password: 123456
    key-store-password: 123456
    key-store: classpath:tomcat.keystore
    key-alias: lazyman

spring:
  application:
    name: pickup-web
  output:
    ansi:
      enabled: detect
  resources:
    static-locations: file:src/main/resources/public

logging:
  register-shutdown-hook: true